patches:
- path: ingress_patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: skiapp-ingress
    version: v1

images:
- name: 180287136233.dkr.ecr.us-west-2.amazonaws.com/skiapp
  newTag: main-7b9df114-95
resources:
- ../../base

