namespace: team-riker
images:
- name: 180287136233.dkr.ecr.us-west-2.amazonaws.com/skiapp
  newName: 180287136233.dkr.ecr.us-west-2.amazonaws.com/skiapp
  newTag: dev-66dc4f59-29
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
