version: 0.2
env:
  shell: bash
  git-credential-helper: yes
phases:
  install:
    commands:
      - git config --global user.name "codecommit"
      - git config --global user.email ""
      - git checkout main
      - git pull origin main
  build:
    commands:
      - cd overlays/dev/
      - kustomize edit set image 180287136233.dkr.ecr.us-west-2.amazonaws.com/skiapp=180287136233.dkr.ecr.us-west-2.amazonaws.com/skiapp:$IMAGE_TAG
      - cat kustomization.yaml
  post_build:
    commands:
      - git add kustomization.yaml && git commit -m "Update Image Tag"
      - git push -u origin main
